version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "joom_calendar"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  joom-calendar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://postgres:postgrespw@postgres:5432/joom_calendar"
      JWT_SECRET: "secret"
      GITHUB_CLIENT_ID: "client_id"
      GITHUB_CLIENT_SECRET: "client_secret"

volumes:
  data:
